### ISSUE TITLE
Icons are too small -> adaptive icon not working?

### ISSUE THREAD

**Issue by amenk** [trufi-association/trotro-app#1]
The Trufi icon was filling the full background of the round icons on Android 10

The icon from the new Troto app now looks like this:

![Selection_205](https://user-images.githubusercontent.com/1087128/67157570-223d5200-f32e-11e9-8ce3-7caa1e84da7f.png)

Do you have an idea what is wrong here?

I was thinking about trying https://pub.dev/packages/flutter_launcher_icons - it seems to support adaptive icons well. But that might be overkill. Maybe the reason is simple?

**Comment by RaimundWege** [comment]
Thanks for testing and reporting. I thought it would be enough to copy the android res-folder. @SamuelRioTz do you know whats missing here?

**Comment by RaimundWege** [comment]
I guess I need the Icons with a transparent background. Trufi icons are still working in this repository. @amenk you said they already worked that means they already exist but where are they?

**Comment by RaimundWege** [comment]
I've created icons with transparent background and it works ... in iOS transparent Icons are forbidden ... it figures!
