### ISSUE TITLE
mapCenterCoordsLatLng and box in both files 

### ISSUE THREAD

**Issue by leoguti** [trufi-association/trotro-app#2]
I have modified the file

assets / cfg / app_config.json

in order to change the center and area of the city of Duitama.

     "mapCenterCoordsLatLng": [5.82303, -73.03762],
     "mapSouthWestCoordsLatLng": [5.76259, -73.09],
     "mapNorthEastCoordsLatLng": [5.86897, -72.98995],

But, in the lib / main.dart file they also appear and I had to change it there to work, I think it is not taking the variables defined in app_config.json

**Comment by amenk** [comment]
Exactly. Is that indented or an error?

**Comment by RaimundWege** [comment]
The new behavior is intended. The config file is no longer part of `trufi_core` but the user of our dependency can still use it in his version of Trufi but he has to pass the config through the singleton instance of`TrufiConfiguration ` widget before ([at this point we set the map center](https://github.com/trufi-association/trotro-app/blob/master/lib/main.dart#L84)).

**Comment by mdoelker** [comment]
You may pull the value out of the JSON and initialize the LatLng object with it.
