### ISSUE TITLE
Changing accentColor in main.dart does not have an effect

### ISSUE THREAD

**Issue by amenk** [trufi-association/trotro-app#5]
Hi changed

	  // Run app
	  runApp(
	    TrufiApp(
	      theme: ThemeData(
		primaryColor: const Color(0xff263238),
		accentColor: const Color(0xff27ae60),  // this line
		backgroundColor: Colors.white,
		primaryColorLight: const Color(0xffeceff1),
	      ),
	      localization: Localization(),
	    ),
	  );

Ran `flutter clean && flutter run` but it does not have an effect. Icons and routes are still Magenta.

**Comment by amenk** [comment]
The plan color seems to be hard coded in

https://github.com/trufi-association/trufi-app/blob/feat/293-generalize-code/lib/plan/plan_map.dart#L319 + https://github.com/trufi-association/trufi-app/blob/feat/293-generalize-code/lib/plan/plan_map.dart#L342

**Comment by amenk** [comment]
Changing this would work - I can try to make a PR to core to pull this form the theme.
But can you give me a hint how the icons are made? (mapmarker, and the circle)
Can they be colorized automatically?

**Comment by amenk** [comment]
Found the markers ... trufi-app/assets/images/from_marker.svg and dep/trufi-app/assets/images/to_marker.svg

**Comment by mdoelker** [comment]
Closing as you have kindly fixed this already :)
